[versions]
kotlin = "2.0.0"
coroutines = "1.8.1"
kotest = "5.9.1"
flyway = "10.17.0"

[libraries]
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version = "7.0.0" }

kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

pg-jdbc = { module = "org.postgresql:postgresql", version = "42.7.3" }
jooq = { module = "org.jooq:jooq", version = "3.19.10" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-postgres = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "coroutines" }
kotlinx-coroutines-slf4j = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-slf4j", version.ref = "coroutines" }

slf4j-simple = { module = "org.slf4j:slf4j-simple", version = "2.0.13" }

testcontainers-postgres = { module = "org.testcontainers:postgresql", version = "1.20.0" }
hikaricp = { module = "com.zaxxer:HikariCP", version = "5.1.0" }

kotest-assertions = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }

junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version = "5.10.3" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

ktlint = { id = "org.jmailen.kotlinter", version = "4.4.1" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.6" }

maven-central-publish = { id = "com.vanniktech.maven.publish", version = "0.29.0" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }

[bundles]
coroutines = ["kotlinx-coroutines-core", "kotlinx-coroutines-reactor", "kotlinx-coroutines-slf4j"]
kotest = ["kotest-assertions"]
junit = ["junit-jupiter-engine"]
flyway = ["flyway-core", "flyway-postgres"]
